#!/usr/bin/env node
// Regenerates the Wizard of Odds house-edge data used by BJSCore's EdgeCalculator.
//
// Downloads WoO's blackjack house edge calculator page, evaluates its inline data script
// (edgeTable + CalculateResult) against a stub form, calls WoO's own CalculateResult() for
// every rule combination the app supports, and reads the "Basic strategy with cut card" box
// (RESULTS7). Writes BJSCore/Sources/BJSCore/Edge/WoOEdgeData.swift.
//
// Usage (from the repo root): node tools/woo-edge/extract.js [repoRoot]
// Dev-only: this executes the page's own script. Review the diff before committing.

const fs = require('fs');
const path = require('path');

const URL = 'https://wizardofodds.com/games/blackjack/calculator/';
const root = process.argv[2] || process.cwd();
const out = path.join(root, 'BJSCore/Sources/BJSCore/Edge/WoOEdgeData.swift');

// The app's deck counts and their radio index on WoO's page (WoO also offers 5 decks, index 3).
const DECKS = [[1, 0], [2, 1], [4, 2], [6, 4], [8, 5]];

function radios(n) {
  return Array.from({ length: n }, () => ({ checked: false }));
}

async function main() {
  const res = await fetch(URL, { headers: { 'User-Agent': 'Mozilla/5.0' } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const html = await res.text();
  const marker = html.indexOf('var edgeTable');
  if (marker < 0) throw new Error('edgeTable not found; page layout changed');
  const start = html.lastIndexOf('<script', marker);
  const src = html.slice(html.indexOf('>', start) + 1, html.indexOf('</script>', marker));
  if (!src.includes('function CalculateResult')) throw new Error('CalculateResult not found; page layout changed');

  const form = {
    SELECT1: radios(6), SELECT2: radios(2), SELECT3: radios(2), SELECT4: radios(3), SELECT5: radios(3),
    SELECT6: radios(2), SELECT7: radios(2), SELECT8: radios(2), SELECT9: radios(2), SELECT10: radios(2),
    RESULTS6: {}, RESULTS7: {}, RESULTS8: {},
  };
  const document = { selectForm: form };
  const window = {};
  const calculate = new Function('document', 'window', `${src}\nreturn CalculateResult;`)(document, window);

  function select(name, index) {
    form[name].forEach((r, i) => { r.checked = i === index; });
  }

  // Index order, outermost first (must match EdgeCalculator.tableIndex):
  // decks(1,2,4,6,8) · soft17(stands,hits) · das(no,yes) · double(any two,9-11,10-11) ·
  // hands(2,3,4) · rsa(no,yes) · hsa(no,yes) · hole card(peek,none) · surrender(none,late) ·
  // payout(3:2,6:5)
  const values = [];
  for (const [, deckIndex] of DECKS)
    for (let h17 = 0; h17 < 2; h17++)
      for (let das = 0; das < 2; das++)
        for (let dbl = 0; dbl < 3; dbl++)
          for (let hands = 0; hands < 3; hands++)
            for (let rsa = 0; rsa < 2; rsa++)
              for (let hsa = 0; hsa < 2; hsa++)
                for (let enhc = 0; enhc < 2; enhc++)
                  for (let ls = 0; ls < 2; ls++)
                    for (let p65 = 0; p65 < 2; p65++) {
                      select('SELECT1', deckIndex);
                      select('SELECT2', h17);
                      select('SELECT3', das);
                      select('SELECT4', dbl);
                      select('SELECT5', hands);
                      select('SELECT6', rsa);
                      select('SELECT7', hsa);
                      select('SELECT8', 1 - enhc); // WoO: "loses only original bet vs BJ" No = no hole card
                      select('SELECT9', ls);
                      select('SELECT10', p65);
                      calculate();
                      const text = String(form.RESULTS7.value);
                      const value = parseFloat(text);
                      if (!text.endsWith('%') || !Number.isFinite(value)) throw new Error(`bad value ${text}`);
                      values.push(value);
                    }
  if (values.length !== 5760) throw new Error(`expected 5760 values, got ${values.length}`);

  const date = new Date().toLocaleDateString('en-CA');
  const lines = [];
  for (let i = 0; i < values.length; i += 8) {
    lines.push('        ' + values.slice(i, i + 8).map(v => String(v)).join(', ') + ',');
  }
  const swift = `// Generated by tools/woo-edge/extract.js. Do not edit by hand.
// Source: ${URL} (retrieved ${date}).
// House edge by WizardOfOdds.com.

/// Wizard of Odds house edge (%) for total-dependent basic strategy dealt with a cut card,
/// one value per rule combination. Index order, outermost first: decks (1, 2, 4, 6, 8) ·
/// soft 17 (stands, hits) · DAS (no, yes) · double (any two, 9-11, 10-11) · hands (2, 3, 4) ·
/// RSA (no, yes) · hit split aces (no, yes) · hole card (peek, none) · surrender (none, late) ·
/// payout (3:2, 6:5). See \`EdgeCalculator.tableIndex\`.
enum WoOEdgeData {
    static let cutCard: [Double] = [
${lines.join('\n')}
    ]
}
`;
  fs.writeFileSync(out, swift);
  console.log(`wrote ${values.length} values to ${out}`);
}

main().catch(e => { console.error(e); process.exit(1); });
