// Generated by tools/woo-strategy/extract.js. Do not edit by hand.
// Source: https://wizardofodds.com/games/blackjack/strategy/calculator/ (retrieved 2026-09-25).
// Strategy by WizardOfOdds.com.

/// Wizard of Odds basic-strategy tables, one per deck group and soft-17 rule.
///
/// Rows 0-16: hard 5-21. Rows 17-25: soft 13-21. Rows 26-35: pairs 2,2 to A,A.
/// Columns 0-7: dealer 2-9. 8: dealer 10. 9: dealer A (American peek).
/// 10: dealer 10 and 11: dealer A under European no hole card.
/// Codes: H, S, DH, DS, P, QH, QD, QS (split if DAS, else hit / double-hit / stand),
/// RH, RS, RP (surrender if allowed, else hit / stand / split).
enum WoOStrategyData {
    static let s17Deck1: [[String]] = [
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 5
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 6
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 7
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // hard 8
        ["DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // hard 9
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // hard 10
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H"],  // hard 11
        ["H", "H", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 12
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 13
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "RH", "RH"],  // hard 14
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "RH", "RH"],  // hard 15
        ["S", "S", "S", "S", "S", "H", "H", "H", "RH", "RH", "RH", "RH"],  // hard 16
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "RS"],  // hard 17
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 18
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 21
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 13
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 14
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 15
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 16
        ["DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 17
        ["S", "DS", "DS", "DS", "DS", "S", "S", "H", "H", "S", "H", "S"],  // soft 18
        ["S", "S", "S", "S", "DS", "S", "S", "S", "S", "S", "S", "S"],  // soft 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 21
        ["QH", "P", "P", "P", "P", "P", "H", "H", "H", "H", "H", "H"],  // pair 2,2
        ["QH", "QH", "P", "P", "P", "P", "QH", "H", "H", "H", "H", "RH"],  // pair 3,3
        ["H", "H", "QH", "QD", "QD", "H", "H", "H", "H", "H", "H", "H"],  // pair 4,4
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // pair 5,5
        ["P", "P", "P", "P", "P", "QH", "H", "H", "H", "H", "H", "RH"],  // pair 6,6
        ["P", "P", "P", "P", "P", "P", "QH", "H", "RS", "H", "RS", "RH"],  // pair 7,7
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "RH", "RH"],  // pair 8,8
        ["P", "P", "P", "P", "P", "S", "P", "P", "S", "S", "S", "S"],  // pair 9,9
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // pair 10,10
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "H"],  // pair A,A
    ]

    static let h17Deck1: [[String]] = [
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 5
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 6
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 7
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // hard 8
        ["DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // hard 9
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // hard 10
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H"],  // hard 11
        ["H", "H", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 12
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 13
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "RH", "RH"],  // hard 14
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "RH", "RH", "RH"],  // hard 15
        ["S", "S", "S", "S", "S", "H", "H", "H", "RH", "RH", "RH", "RH"],  // hard 16
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "RS", "S", "RS"],  // hard 17
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 18
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 21
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 13
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 14
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 15
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 16
        ["DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 17
        ["S", "DS", "DS", "DS", "DS", "S", "S", "H", "H", "H", "H", "H"],  // soft 18
        ["S", "S", "S", "S", "DS", "S", "S", "S", "S", "S", "S", "S"],  // soft 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 21
        ["QH", "P", "P", "P", "P", "P", "H", "H", "H", "H", "H", "RH"],  // pair 2,2
        ["QH", "QH", "P", "P", "P", "P", "QH", "H", "H", "H", "H", "RH"],  // pair 3,3
        ["H", "H", "QH", "QD", "QD", "H", "H", "H", "H", "H", "H", "H"],  // pair 4,4
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // pair 5,5
        ["P", "P", "P", "P", "P", "QH", "H", "H", "H", "H", "H", "RH"],  // pair 6,6
        ["P", "P", "P", "P", "P", "P", "QH", "H", "RS", "RH", "RS", "RH"],  // pair 7,7
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "RH", "RH"],  // pair 8,8
        ["P", "P", "P", "P", "P", "S", "P", "P", "S", "QS", "S", "S"],  // pair 9,9
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // pair 10,10
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "H"],  // pair A,A
    ]

    static let s17Deck2: [[String]] = [
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 5
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 6
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 7
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],  // hard 8
        ["DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // hard 9
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // hard 10
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H"],  // hard 11
        ["H", "H", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 12
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 13
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "RH", "RH"],  // hard 14
        ["S", "S", "S", "S", "S", "H", "H", "H", "RH", "H", "RH", "RH"],  // hard 15
        ["S", "S", "S", "S", "S", "H", "H", "H", "RH", "RH", "RH", "RH"],  // hard 16
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "RS"],  // hard 17
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 18
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 21
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 13
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 14
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 15
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 16
        ["H", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 17
        ["S", "DS", "DS", "DS", "DS", "S", "S", "H", "H", "H", "H", "H"],  // soft 18
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 21
        ["QH", "QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "H"],  // pair 2,2
        ["QH", "QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "RH"],  // pair 3,3
        ["H", "H", "H", "QH", "QH", "H", "H", "H", "H", "H", "H", "H"],  // pair 4,4
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // pair 5,5
        ["P", "P", "P", "P", "P", "QH", "H", "H", "H", "H", "H", "RH"],  // pair 6,6
        ["P", "P", "P", "P", "P", "P", "QH", "H", "H", "H", "RH", "RH"],  // pair 7,7
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "RH", "RH"],  // pair 8,8
        ["P", "P", "P", "P", "P", "S", "P", "P", "S", "S", "S", "S"],  // pair 9,9
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // pair 10,10
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "H"],  // pair A,A
    ]

    static let h17Deck2: [[String]] = [
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 5
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 6
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 7
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],  // hard 8
        ["DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // hard 9
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // hard 10
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H"],  // hard 11
        ["H", "H", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 12
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 13
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "RH", "RH"],  // hard 14
        ["S", "S", "S", "S", "S", "H", "H", "H", "RH", "RH", "RH", "RH"],  // hard 15
        ["S", "S", "S", "S", "S", "H", "H", "H", "RH", "RH", "RH", "RH"],  // hard 16
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "RS", "S", "RS"],  // hard 17
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 18
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 21
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 13
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 14
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 15
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 16
        ["H", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 17
        ["DS", "DS", "DS", "DS", "DS", "S", "S", "H", "H", "H", "H", "H"],  // soft 18
        ["S", "S", "S", "S", "DS", "S", "S", "S", "S", "S", "S", "S"],  // soft 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 21
        ["QH", "QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "RH"],  // pair 2,2
        ["QH", "QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "RH"],  // pair 3,3
        ["H", "H", "H", "QH", "QH", "H", "H", "H", "H", "H", "H", "H"],  // pair 4,4
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // pair 5,5
        ["P", "P", "P", "P", "P", "QH", "H", "H", "H", "H", "H", "RH"],  // pair 6,6
        ["P", "P", "P", "P", "P", "P", "QH", "H", "H", "H", "RH", "RH"],  // pair 7,7
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "RP", "RH", "RH"],  // pair 8,8
        ["P", "P", "P", "P", "P", "S", "P", "P", "S", "S", "S", "S"],  // pair 9,9
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // pair 10,10
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "H"],  // pair A,A
    ]

    static let s17Deck4Plus: [[String]] = [
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 5
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 6
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 7
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],  // hard 8
        ["H", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // hard 9
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // hard 10
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H"],  // hard 11
        ["H", "H", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 12
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 13
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "RH", "RH"],  // hard 14
        ["S", "S", "S", "S", "S", "H", "H", "H", "RH", "H", "RH", "RH"],  // hard 15
        ["S", "S", "S", "S", "S", "H", "H", "RH", "RH", "RH", "RH", "RH"],  // hard 16
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "RS"],  // hard 17
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 18
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 21
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 13
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 14
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 15
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 16
        ["H", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 17
        ["S", "DS", "DS", "DS", "DS", "S", "S", "H", "H", "H", "H", "H"],  // soft 18
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 21
        ["QH", "QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "H"],  // pair 2,2
        ["QH", "QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "RH"],  // pair 3,3
        ["H", "H", "H", "QH", "QH", "H", "H", "H", "H", "H", "H", "H"],  // pair 4,4
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // pair 5,5
        ["QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "H", "RH"],  // pair 6,6
        ["P", "P", "P", "P", "P", "P", "H", "H", "H", "H", "RH", "RH"],  // pair 7,7
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "RH", "RH"],  // pair 8,8
        ["P", "P", "P", "P", "P", "S", "P", "P", "S", "S", "S", "S"],  // pair 9,9
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // pair 10,10
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "H"],  // pair A,A
    ]

    static let h17Deck4Plus: [[String]] = [
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 5
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 6
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "RH"],  // hard 7
        ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],  // hard 8
        ["H", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // hard 9
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // hard 10
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H"],  // hard 11
        ["H", "H", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 12
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "H", "RH"],  // hard 13
        ["S", "S", "S", "S", "S", "H", "H", "H", "H", "H", "RH", "RH"],  // hard 14
        ["S", "S", "S", "S", "S", "H", "H", "H", "RH", "RH", "RH", "RH"],  // hard 15
        ["S", "S", "S", "S", "S", "H", "H", "RH", "RH", "RH", "RH", "RH"],  // hard 16
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "RS", "S", "RS"],  // hard 17
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 18
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // hard 21
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 13
        ["H", "H", "H", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 14
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 15
        ["H", "H", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 16
        ["H", "DH", "DH", "DH", "DH", "H", "H", "H", "H", "H", "H", "H"],  // soft 17
        ["DS", "DS", "DS", "DS", "DS", "S", "S", "H", "H", "H", "H", "H"],  // soft 18
        ["S", "S", "S", "S", "DS", "S", "S", "S", "S", "S", "S", "S"],  // soft 19
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 20
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // soft 21
        ["QH", "QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "RH"],  // pair 2,2
        ["QH", "QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "RH"],  // pair 3,3
        ["H", "H", "H", "QH", "QH", "H", "H", "H", "H", "H", "H", "H"],  // pair 4,4
        ["DH", "DH", "DH", "DH", "DH", "DH", "DH", "DH", "H", "H", "H", "H"],  // pair 5,5
        ["QH", "P", "P", "P", "P", "H", "H", "H", "H", "H", "H", "RH"],  // pair 6,6
        ["P", "P", "P", "P", "P", "P", "H", "H", "H", "H", "RH", "RH"],  // pair 7,7
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "RP", "RH", "RH"],  // pair 8,8
        ["P", "P", "P", "P", "P", "S", "P", "P", "S", "S", "S", "S"],  // pair 9,9
        ["S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S", "S"],  // pair 10,10
        ["P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "H"],  // pair A,A
    ]
}
