/// A rule that moves the house edge away from WoO's baseline game. Cases are listed in
/// attribution order (see `EdgeCalculator.analyze(rules:)`).
public enum EdgeFactor: Sendable, Hashable {
    case decks(BlackjackRules.DeckCount)
    case dealerHitsSoft17
    case payout(BlackjackRules.BlackjackPayout)
    case noDoubleAfterSplit
    case doubleRestriction(BlackjackRules.DoubleRestriction)
    case maxSplitHands(Int)
    case resplitAces
    case hitSplitAces
    case noHoleCard
    /// `pricedAsEarly` is true for late surrender under no hole card, which `RoundEngine`
    /// settles like early surrender (it honours the surrender even against a natural).
    case surrender(BlackjackRules.SurrenderRule, pricedAsEarly: Bool)
}

/// One step of the breakdown: how much this rule changes the house edge, in percentage points
/// (positive is worse for the player), given every rule before it in attribution order.
public struct RuleContribution: Sendable, Hashable {
    public let factor: EdgeFactor
    public let edgeChange: Double

    public init(factor: EdgeFactor, edgeChange: Double) {
        self.factor = factor
        self.edgeChange = edgeChange
    }
}

/// The house edge for a rule set, with its breakdown from WoO's baseline game.
public struct EdgeResult: Sendable, Hashable {
    /// House edge in percent (0.43 means 0.43%). Negative means the player has the edge.
    public let houseEdge: Double
    /// Steps from `EdgeCalculator.baselineRules`. They sum exactly to
    /// `houseEdge - EdgeCalculator.baselineHouseEdge`.
    public let contributions: [RuleContribution]

    public init(houseEdge: Double, contributions: [RuleContribution]) {
        self.houseEdge = houseEdge
        self.contributions = contributions
    }
}

/// House edge for total-dependent basic strategy dealt with a cut card, from Wizard of Odds'
/// house edge calculator (`WoOEdgeData`, generated by `tools/woo-edge/extract.js`).
///
/// Two rules the calculator doesn't offer are derived:
/// - 2:1 payouts, exactly: the payout is linear in unpushed player blackjacks and basic
///   strategy ignores it, so 2:1 (+0.5 units per blackjack against 3:2) sits 5/3 of the
///   3:2 → 6:5 gap (−0.3 units) on the other side of 3:2.
/// - Early surrender: WoO's rule-variation figures (8 decks), not deck-specific.
public struct EdgeCalculator: Sendable {

    /// WoO rule variations (8 decks): early surrender against an ace +0.39% and against a ten
    /// +0.24% for the player.
    public static let earlySurrenderGain = 0.63

    /// WoO's baseline game: 8 decks, S17, DAS, double any two, split to 4 hands, no RSA,
    /// no hit split aces, peek, no surrender, 3:2.
    public static let baselineRules: BlackjackRules = {
        var rules = BlackjackRules()
        rules.deckCount = .eight
        return rules
    }()

    public static let baselineHouseEdge: Double = EdgeCalculator().houseEdge(for: baselineRules)

    public init() {}

    public func houseEdge(for rules: BlackjackRules) -> Double {
        let surrender = Self.effectiveSurrender(rules)
        func table(sixToFive: Bool) -> Double {
            WoOEdgeData.cutCard[Self.tableIndex(rules, lateSurrender: surrender == .late, sixToFive: sixToFive)]
        }
        var edge: Double
        switch rules.blackjackPayout {
        case .threeToTwo:
            edge = table(sixToFive: false)
        case .sixToFive:
            edge = table(sixToFive: true)
        case .twoToOne:
            let threeToTwo = table(sixToFive: false)
            edge = threeToTwo - 5.0 / 3.0 * (table(sixToFive: true) - threeToTwo)
        }
        if surrender == .early { edge -= Self.earlySurrenderGain }
        return edge
    }

    /// The house edge plus its breakdown. Starting from `baselineRules`, the user's rules are
    /// applied one field at a time in `EdgeFactor` order; each changed field records the change
    /// in house edge at that step.
    public func analyze(rules: BlackjackRules) -> EdgeResult {
        let base = Self.baselineRules
        var current = base
        var edge = houseEdge(for: current)
        var contributions: [RuleContribution] = []

        func step(_ changed: Bool, _ factor: EdgeFactor, _ apply: (inout BlackjackRules) -> Void) {
            guard changed else { return }
            apply(&current)
            let next = houseEdge(for: current)
            contributions.append(RuleContribution(factor: factor, edgeChange: next - edge))
            edge = next
        }

        step(rules.deckCount != base.deckCount, .decks(rules.deckCount)) { $0.deckCount = rules.deckCount }
        step(rules.dealerSoft17 != base.dealerSoft17, .dealerHitsSoft17) { $0.dealerSoft17 = rules.dealerSoft17 }
        step(rules.blackjackPayout != base.blackjackPayout, .payout(rules.blackjackPayout)) {
            $0.blackjackPayout = rules.blackjackPayout
        }
        step(rules.doubleAfterSplit != base.doubleAfterSplit, .noDoubleAfterSplit) {
            $0.doubleAfterSplit = rules.doubleAfterSplit
        }
        step(rules.doubleRestriction != base.doubleRestriction, .doubleRestriction(rules.doubleRestriction)) {
            $0.doubleRestriction = rules.doubleRestriction
        }
        step(rules.maxSplitHands != base.maxSplitHands, .maxSplitHands(rules.maxSplitHands)) {
            $0.maxSplitHands = rules.maxSplitHands
        }
        step(rules.resplitAces != base.resplitAces, .resplitAces) { $0.resplitAces = rules.resplitAces }
        step(rules.hitSplitAces != base.hitSplitAces, .hitSplitAces) { $0.hitSplitAces = rules.hitSplitAces }
        step(rules.peekRule != base.peekRule, .noHoleCard) { $0.peekRule = rules.peekRule }
        let lateAsEarly = rules.surrenderRule == .late && rules.peekRule == .europeanNoPeek
        step(rules.surrenderRule != base.surrenderRule, .surrender(rules.surrenderRule, pricedAsEarly: lateAsEarly)) {
            $0.surrenderRule = rules.surrenderRule
        }

        return EdgeResult(houseEdge: edge, contributions: contributions)
    }

    // MARK: - Table

    /// Late surrender under no hole card settles like early surrender in `RoundEngine`.
    static func effectiveSurrender(_ rules: BlackjackRules) -> BlackjackRules.SurrenderRule {
        rules.surrenderRule == .late && rules.peekRule == .europeanNoPeek ? .early : rules.surrenderRule
    }

    /// Index into `WoOEdgeData.cutCard`. The order must match `tools/woo-edge/extract.js`:
    /// decks · soft 17 · DAS · double · hands · RSA · HSA · hole card · late surrender · 6:5.
    static func tableIndex(_ rules: BlackjackRules, lateSurrender: Bool, sixToFive: Bool) -> Int {
        let decks: Int = switch rules.deckCount {
        case .one: 0
        case .two: 1
        case .four: 2
        case .six: 3
        case .eight: 4
        }
        let double: Int = switch rules.doubleRestriction {
        case .anyTwo: 0
        case .nineToEleven: 1
        case .tenToEleven: 2
        }
        let hands = min(max(rules.maxSplitHands, 2), 4) - 2
        var index = decks
        index = index * 2 + (rules.dealerSoft17 == .hits ? 1 : 0)
        index = index * 2 + (rules.doubleAfterSplit ? 1 : 0)
        index = index * 3 + double
        index = index * 3 + hands
        index = index * 2 + (rules.resplitAces ? 1 : 0)
        index = index * 2 + (rules.hitSplitAces ? 1 : 0)
        index = index * 2 + (rules.peekRule == .europeanNoPeek ? 1 : 0)
        index = index * 2 + (lateSurrender ? 1 : 0)
        index = index * 2 + (sixToFive ? 1 : 0)
        return index
    }
}
