#!/usr/bin/env node
// Regenerates the Wizard of Odds basic-strategy data used by BJSCore.
//
// Downloads WoO's strategy calculator page, evaluates its data script with a
// stub DOM, and writes:
//   - the six raw tables as Swift (BJSCore/Sources/BJSCore/Strategy/WoOStrategyData.swift)
//   - WoO's own rendered charts for 48 rule combinations as a Swift test fixture
//     (BJSCore/Tests/BJSCoreTests/StrategyTests/WoORenderedCharts.swift)
//
// Usage (from the repo root): node tools/woo-strategy/extract.js [repoRoot]
// Dev-only: this executes the page's own script. Review the diff before committing.

const fs = require('fs');
const path = require('path');

const URL = 'https://wizardofodds.com/games/blackjack/strategy/calculator/';
const root = process.argv[2] || process.cwd();
const dataOut = path.join(root, 'BJSCore/Sources/BJSCore/Strategy/WoOStrategyData.swift');
const fixtureOut = path.join(root, 'BJSCore/Tests/BJSCoreTests/StrategyTests/WoORenderedCharts.swift');

async function main() {
  const res = await fetch(URL, { headers: { 'User-Agent': 'Mozilla/5.0' } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const html = await res.text();
  const start = html.indexOf('// 1 DECK, DEALER HITS SOFT 17');
  if (start < 0) throw new Error('data script not found; page layout changed');
  const src = html.slice(start, html.indexOf('</script>', start));

  const selects = {};
  for (const id of ['decks', 'soft17', 'das', 'surr', 'peek']) selects[id] = { selectedIndex: 0 };
  let rendered = '';
  const document = {
    getElementById: id => (id === 'strategy' ? { set innerHTML(v) { rendered = v; } } : selects[id]),
  };
  const run = new Function('document',
    src + '\nreturn { H17_0, S17_0, H17_1, S17_1, H17_2, S17_2, ComputeStrategy };');
  const woo = run(document);

  const date = new Date().toISOString().slice(0, 10);
  const header = [
    '// Generated by tools/woo-strategy/extract.js. Do not edit by hand.',
    `// Source: ${URL} (retrieved ${date}).`,
    '// Strategy by WizardOfOdds.com.',
  ];

  // --- Raw tables -> Swift ---
  const rowNames = [];
  for (let t = 5; t <= 21; t++) rowNames.push(`hard ${t}`);
  for (let t = 13; t <= 21; t++) rowNames.push(`soft ${t}`);
  for (const p of ['2,2', '3,3', '4,4', '5,5', '6,6', '7,7', '8,8', '9,9', '10,10', 'A,A']) rowNames.push(`pair ${p}`);
  const tables = [
    ['s17Deck1', woo.S17_0], ['h17Deck1', woo.H17_0],
    ['s17Deck2', woo.S17_1], ['h17Deck2', woo.H17_1],
    ['s17Deck4Plus', woo.S17_2], ['h17Deck4Plus', woo.H17_2],
  ];
  const swift = [...header, '',
    '/// Wizard of Odds basic-strategy tables, one per deck group and soft-17 rule.',
    '///',
    '/// Rows 0-16: hard 5-21. Rows 17-25: soft 13-21. Rows 26-35: pairs 2,2 to A,A.',
    '/// Columns 0-7: dealer 2-9. 8: dealer 10. 9: dealer A (American peek).',
    '/// 10: dealer 10 and 11: dealer A under European no hole card.',
    '/// Codes: H, S, DH, DS, P, QH, QD, QS (split if DAS, else hit / double-hit / stand),',
    '/// RH, RS, RP (surrender if allowed, else hit / stand / split).',
    'enum WoOStrategyData {'];
  for (const [name, table] of tables) {
    if (table.length !== 36 || table.some(r => r.length !== 12)) throw new Error(`${name}: bad shape`);
    swift.push(`    static let ${name}: [[String]] = [`);
    table.forEach((row, i) => {
      swift.push(`        [${row.map(c => `"${c}"`).join(', ')}],  // ${rowNames[i]}`);
    });
    swift.push('    ]', '');
  }
  swift[swift.length - 1] = '}';
  fs.writeFileSync(dataOut, swift.join('\n') + '\n');

  // --- Rendered charts (WoO's own decoding) -> Swift fixture ---
  const lines = [];
  const deckNames = ['1', '2', '4+'];
  for (let dk = 0; dk < 3; dk++) for (let s17 = 0; s17 < 2; s17++) for (let das = 0; das < 2; das++)
  for (const su of [0, 1]) for (let pk = 0; pk < 2; pk++) {
    selects.decks.selectedIndex = dk; selects.soft17.selectedIndex = s17;
    selects.das.selectedIndex = das; selects.surr.selectedIndex = su; selects.peek.selectedIndex = pk;
    woo.ComputeStrategy();
    const rows = [...rendered.matchAll(/<tr><th>([^<]+)<\/th>((?:<td[^>]*>[^<]*<\/td>){10})<\/tr>/g)];
    if (rows.length !== 36) throw new Error(`expected 36 rows, got ${rows.length}`);
    lines.push(`# decks=${deckNames[dk]} soft17=${s17 ? 'H17' : 'S17'} das=${das ? 'no' : 'yes'} ` +
               `surrender=${su ? 'any' : 'none'} peek=${pk ? 'enhc' : 'peek'}`);
    rows.forEach((r, i) => {
      const cells = [...r[2].matchAll(/>([^<]*)<\/td>/g)].map(m => m[1]);
      const section = i < 17 ? 'H' : i < 26 ? 'S' : 'P';
      lines.push(`${section}${r[1].replace(',', '-')} ${cells.join(' ')}`);
    });
  }
  const fixture = [...header, '',
    '/// WoO\'s rendered charts: 3 deck groups x S17/H17 x DAS yes/no x surrender none/any x peek/ENHC.',
    '/// Each chart: a "# key" line, then 36 rows (H5-H21, S13-S21, P2-2..PA-A) of 10 display codes',
    '/// for dealer 2-9, 10, A. Codes: H S Dh Ds P Rh Rs Rp.',
    'let wooRenderedCharts = """',
    ...lines,
    '"""'];
  fs.writeFileSync(fixtureOut, fixture.join('\n') + '\n');
  console.log(`wrote ${dataOut}\nwrote ${fixtureOut} (${lines.filter(l => l.startsWith('#')).length} charts)`);
}

main().catch(e => { console.error(e); process.exit(1); });
